apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: dafina22/atwork-backend:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: DB_SERVER
              value: "database-service"
            - name: DB_NAME
              value: "TaxiApp"
            - name: DB_USER
              value: "sa"
            - name: DB_PASSWORD
              value: "Ditelindja123."
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
