apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000        # The port the service will expose
      targetPort: 8080  # The port your backend container is listening on
  type: NodePort        # Expose the service externally via a node port
