apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP